spring:
  application:
    name: Customer_Management_Services

  datasource:
    url: jdbc:mysql://localhost:3306/testschema
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:2580}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # Automatically updates schema in dev
    show-sql: true       # Shows SQL queries in console
    properties:
      hibernate:
        format_sql: true # Pretty print SQL
        dialect: org.hibernate.dialect.MySQL8Dialect

# Server Configuration
server:
  port: 8080

# Logging Configuration
logging:
  level:
    com.SprCustomers: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Swagger/OpenAPI Configuration
